# NOTE: this file must replace the gloabl_config.toml 
# once the bridging PR is ready to deploy on mainnet
[invoke.periphery_global_config]
target = ["PeripheryProxy"]
fromCall.func = "owner"
func = "setGlobalConfiguration"
args = [
    { coreProxy = "<%= contracts.CoreProxy.address %>", rUSDProxy = "<%= contracts.RUSDProxy.address %>", passivePoolProxy = "<%= contracts.PassivePoolProxy.address %>", layerZeroEndpoint = "<%= settings.reyaLayerZeroEndpoint %>", sREYAProxy = "<%= settings.sreyaProxy %>", REYAProxy = "<%= settings.reyaProxy %>" },
]
depends = [
    "invoke.upgrade_periphery_proxy",
    "invoke.upgrade_core_proxy",
    "var.external_contracts",
    "var.rusd_complete",
]
