[invoke.passive_perp_depth_config_owner]
target = ["PassivePerpProxy"]
fromCall.func = "owner"
func = "addToFeatureFlagAllowlist"
args = ["<%= keccak256(hexlify('configureDepth')) %>", "<%= settings.owner %>"]
depends = ["invoke.upgrade_passive_perp_proxy"]

[invoke.passive_perp_initialize_depth_factors]
target = ["PassivePerpProxy"]
fromCall.func = "owner"
func = "batchSetMarketConfigurationDepth"
args = [
    [
        "<%= settings.market1EthId %>",
        "<%= settings.market2BtcId %>",
        "<%= settings.market3SolId %>",
        "<%= settings.market4ArbId %>",
        "<%= settings.market5OpId %>",
        "<%= settings.market6AvaxId %>",
        "<%= settings.market7MkrId %>",
        "<%= settings.market8LinkId %>",
        "<%= settings.market9AaveId %>",
        "<%= settings.market10CrvId %>",
        "<%= settings.market11UniId %>",
        "<%= settings.market12SuiId %>",
        "<%= settings.market13TiaId %>",
        "<%= settings.market14SeiId %>",
        "<%= settings.market15ZroId %>",
        "<%= settings.market16XrpId %>",
        "<%= settings.market17WifId %>",
        "<%= settings.market18Pepe1kId %>",
        "<%= settings.market19PopcatId %>",
        "<%= settings.market20DogeId %>",
        "<%= settings.market21KShibId %>",
        "<%= settings.market22KBonkId %>",
        "<%= settings.market23AptId %>",
        "<%= settings.market24BnbId %>",
        "<%= settings.market25JtoId %>",
        "<%= settings.market26AdaId %>",
        "<%= settings.market27LdoId %>",
        "<%= settings.market28PolId %>",
        "<%= settings.market29NearId %>",
        "<%= settings.market30FtmId %>",
        "<%= settings.market31EnaId %>",
        "<%= settings.market32EigenId %>",
        "<%= settings.market33PendleId %>",
        "<%= settings.market34GoatId %>",
        "<%= settings.market35GrassId %>",
        "<%= settings.market36KNeiroId %>",
        "<%= settings.market37DotId %>",
        "<%= settings.market38LtcId %>",
        "<%= settings.market39PythId %>",
        "<%= settings.market40JupId %>",
        "<%= settings.market41PenguId %>",
        "<%= settings.market42TrumpId %>",
        "<%= settings.market43HypeId %>",
        "<%= settings.market44VirtualId %>",
        "<%= settings.market45Ai16zId %>",
        "<%= settings.market46AixbtId %>",
        "<%= settings.market47SonicId %>",
        "<%= settings.market48FartcoinId %>",
        "<%= settings.market49GriffainId %>",
        "<%= settings.market50WldId %>",
        "<%= settings.market51AtomId %>",
        "<%= settings.market52ApeId %>",
        "<%= settings.market53TonId %>",
        "<%= settings.market54OndoId %>",
        "<%= settings.market55TrxId %>",
        "<%= settings.market56InjId %>",
        "<%= settings.market57MoveId %>",
        "<%= settings.market58BeraId %>",
        "<%= settings.market59LayerId %>",
        "<%= settings.market60TaoId %>",
        "<%= settings.market61IpId %>",
        "<%= settings.market62MeId %>",
        "<%= settings.market63PumpId %>",
        "<%= settings.market64MorphoId %>",
        "<%= settings.market65SyrupId %>",
        "<%= settings.market66AeroId %>",
        "<%= settings.market67KaitoId %>",
        "<%= settings.market68ZoraId %>",
        "<%= settings.market69ProveId %>",
        "<%= settings.market70PaxgId %>",
        "<%= settings.market71YzyId %>",
        "<%= settings.market72XplId %>",
        "<%= settings.market73WlfiId %>",
        "<%= settings.market74LineaId %>",
        "<%= settings.market75MegaId %>",
    ],
    [
        "<%= parseEther(settings.market1Eth_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market2Btc_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market3Sol_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market4Arb_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market5Op_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market6Avax_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market7Mkr_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market8Link_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market9Aave_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market10Crv_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market11Uni_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market12Sui_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market13Tia_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market14Sei_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market15Zro_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market16Xrp_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market17Wif_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market18Pepe1k_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market19Popcat_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market20Doge_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market21KShib_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market22KBonk_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market23Apt_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market24Bnb_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market25Jto_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market26Ada_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market27Ldo_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market28Pol_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market29Near_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market30Ftm_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market31Ena_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market32Eigen_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market33Pendle_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market34Goat_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market35Grass_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market36KNeiro_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market37Dot_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market38Ltc_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market39Pyth_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market40Jup_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market41Pengu_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market42Trump_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market43Hype_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market44Virtual_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market45Ai16z_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market46Aixbt_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market47Sonic_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market48Fartcoin_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market49Griffain_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market50Wld_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market51Atom_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market52Ape_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market53Ton_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market54Ondo_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market55Trx_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market56Inj_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market57Move_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market58Bera_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market59Layer_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market60Tao_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market61Ip_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market62Me_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market63Pump_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market64Morpho_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market65Syrup_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market66Aero_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market67Kaito_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market68Zora_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market69Prove_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market70Paxg_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market71Yzy_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market72Xpl_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market73Wlfi_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market74Linea_depthFactorUnscaled) %>",
        "<%= parseEther(settings.market75Mega_depthFactorUnscaled) %>",
    ],
]
depends = [
    "invoke.passive_perp_depth_config_owner",
    "invoke.create_market_75mega",
]
