[invoke.passive_perp_depth_config_1]
target = ["PassivePerpProxy"]
fromCall.func = "owner"
func = "addToFeatureFlagAllowlist"
args = [
    "<%= keccak256(hexlify('configureDepth')) %>",
    "<%= settings.co_execution_bot1 %>",
]
depends = ["invoke.upgrade_passive_perp_proxy"]

[invoke.passive_perp_depth_config_2]
target = ["PassivePerpProxy"]
fromCall.func = "owner"
func = "addToFeatureFlagAllowlist"
args = [
    "<%= keccak256(hexlify('configureDepth')) %>",
    "<%= settings.co_execution_bot2 %>",
]
depends = ["invoke.upgrade_passive_perp_proxy"]

[invoke.passive_perp_depth_config_3]
target = ["PassivePerpProxy"]
fromCall.func = "owner"
func = "addToFeatureFlagAllowlist"
args = [
    "<%= keccak256(hexlify('configureDepth')) %>",
    "<%= settings.co_execution_bot3 %>",
]
depends = ["invoke.upgrade_passive_perp_proxy"]

[invoke.passive_perp_depth_config_4]
target = ["PassivePerpProxy"]
fromCall.func = "owner"
func = "addToFeatureFlagAllowlist"
args = [
    "<%= keccak256(hexlify('configureDepth')) %>",
    "<%= settings.co_execution_bot4 %>",
]
depends = ["invoke.upgrade_passive_perp_proxy"]

[invoke.passive_perp_depth_config_5]
target = ["PassivePerpProxy"]
fromCall.func = "owner"
func = "addToFeatureFlagAllowlist"
args = [
    "<%= keccak256(hexlify('configureDepth')) %>",
    "<%= settings.co_execution_bot5 %>",
]
depends = ["invoke.upgrade_passive_perp_proxy"]

[invoke.passive_perp_depth_config_6]
target = ["PassivePerpProxy"]
fromCall.func = "owner"
func = "addToFeatureFlagAllowlist"
args = [
    "<%= keccak256(hexlify('configureDepth')) %>",
    "<%= settings.co_execution_bot6 %>",
]
depends = ["invoke.upgrade_passive_perp_proxy"]

[invoke.passive_perp_depth_config_7]
target = ["PassivePerpProxy"]
fromCall.func = "owner"
func = "addToFeatureFlagAllowlist"
args = [
    "<%= keccak256(hexlify('configureDepth')) %>",
    "<%= settings.co_execution_bot7 %>",
]
depends = ["invoke.upgrade_passive_perp_proxy"]
