# Variable mapping for Ethereum -> Reya
# Ethereum is SOURCE, Reya is DESTINATION

[var.layerzero_source_config]
sourceEndpointAddress = "<%= settings.ethereumEndpointAddress %>"
sourceOAppAddress = "<%= settings.ethereumOAppAddress %>"
sourceSendLibAddress = "<%= settings.ethereumSendLibAddress %>"
sourceReceiveLibAddress = "<%= settings.ethereumReceiveLibAddress %>"
sourceEid = "<%= settings.ethereumEid %>"
sourceExecutorAddress = "<%= settings.ethereumExecutorAddress %>"
sourceLzRequiredDVN1 = "<%= settings.ethereumLzRequiredDVN1 %>"
sourceLzConfirmations = "<%= settings.ethereumLzConfirmations %>"

[var.layerzero_destination_config]
destinationEndpointAddress = "<%= settings.reyaEndpointAddress %>"
destinationOAppAddress = "<%= settings.reyaOAppAddress %>"
destinationSendLibAddress = "<%= settings.reyaSendLibAddress %>"
destinationReceiveLibAddress = "<%= settings.reyaReceiveLibAddress %>"
destinationEid = "<%= settings.reyaEid %>"
destinationExecutorAddress = "<%= settings.reyaExecutorAddress %>"
destinationLzRequiredDVN1 = "<%= settings.reyaLzRequiredDVN1 %>"
destinationLzConfirmations = "<%= settings.reyaLzConfirmations %>"
