[clone.reyaIcoDistributionContract]
source = "<%= settings.reyaIcoDistributionContractPackage %>"
target = "<%= settings.reyaIcoDistributionContractPackage %>"
options.tokenAddress = "<%= settings.reyaTokenProxy %>"
options.totalAllocationUnscaled = "<%= settings.totalAllocationUnscaled %>"
options.owner = "<%= settings.foundationEoa %>"
depends = ["var.cannonClonePackages", "var.ico", "var.upgrade_proxy_vars"]