[invoke.reya_global_collateral_config]
target = ["CoreProxy"]
fromCall.func = "owner"
func = "setGlobalCollateralConfig"
args = [
    "<%= settings.reyaProxy %>",
    { collateralAdapter_DEPRECATED = "<%= settings.reyaCollateralAdapter %>", withdrawalWindowSize = "<%= settings.reyaWithdrawalWindowSize %>", withdrawalTvlPercentageLimit = "<%= parseEther(settings.reyaWithdrawalTvlPercentageLimitUnscaled)  %>" },
]
depends = [
    'invoke.upgrade_core_proxy',
    'var.external_contracts',
    'var.global_collateral_configs',
]
