[invoke.sreya_global_collateral_config]
target = ["CoreProxy"]
fromCall.func = "owner"
func = "setGlobalCollateralConfig"
args = [
    "<%= contracts.SREYAProxy.address %>",
    { collateralAdapter = "<%= settings.sreyaCollateralAdapter %>", withdrawalWindowSize = "<%= settings.sreyaWithdrawalWindowSize %>", withdrawalTvlPercentageLimit = "<%= parseEther(settings.sreyaWithdrawalTvlPercentageLimitUnscaled)  %>" },
]
depends = [
    'invoke.upgrade_core_proxy',
    'var.global_collateral_configs',
]