#####################################
# Create Market
#####################################
[invoke.create_market_9aave]
target = ["PassivePerpProxy"]
abi = "<%= JSON.stringify(contracts.PassivePerpProxy.abi.concat({'type':'event','name':'MarketDataUpdated','inputs':[{'name':'marketData','type':'tuple','indexed':false,'internalType':'struct Market.Data','components':[{'name':'id','type':'uint128','internalType':'uint128'},{'name':'passivePoolId','type':'uint128','internalType':'uint128'},{'name':'poolAccountId','type':'uint128','internalType':'uint128'},{'name':'quoteToken','type':'address','internalType':'address'},{'name':'quoteTokenDecimals','type':'uint8','internalType':'uint8'},{'name':'lastFundingVelocity','type':'int256','internalType':'SD59x18'},{'name':'lastFundingRate','type':'int256','internalType':'SD59x18'},{'name':'lastFundingTimestamp','type':'uint256','internalType':'uint256'},{'name':'lastMTM','type':'tuple','internalType':'struct PriceData','components':[{'name':'price','type':'uint256','internalType':'UD60x18'},{'name':'timestamp','type':'uint256','internalType':'uint256'}]},{'name':'longTrackers','type':'tuple','internalType':'struct FundingAndADLTrackers','components':[{'name':'fundingValue','type':'int256','internalType':'SD59x18'},{'name':'baseMultiplier','type':'uint256','internalType':'UD60x18'},{'name':'adlUnwindPrice','type':'uint256','internalType':'UD60x18'}]},{'name':'shortTrackers','type':'tuple','internalType':'struct FundingAndADLTrackers','components':[{'name':'fundingValue','type':'int256','internalType':'SD59x18'},{'name':'baseMultiplier','type':'uint256','internalType':'UD60x18'},{'name':'adlUnwindPrice','type':'uint256','internalType':'UD60x18'}]},{'name':'openInterest','type':'uint256','internalType':'UD60x18'}]},{'name':'blockTimestamp','type':'uint256','indexed':false,'internalType':'uint256'}],'anonymous':false})) %>"
fromCall.func = "owner"
func = "createMarket"
args = ["Market AAVE", "<%= settings.pool1RusdId %>"]
var.market_9aave.event = "MarketDataUpdated"
var.market_9aave.arg = 0
depends = [
    "invoke.core_register_instrument_passive_perp",
    "invoke.passive_pool_create_pool_1rusd",
    "invoke.create_market_8link",
]

[var.market_9aave_vars]
market9AaveId = "<%= (String(settings.market_9aave.id) === '9') ? settings.market_9aave.id : parseUnits('0', 'assert market_9aave_vars failed') %>"
depends = ["invoke.create_market_9aave"]

##################################################
# Market's Collateral Pool Feature Flags
##################################################
[invoke.market_9aave_unpause_cp]
target = ["CoreProxy"]
fromCall.func = "getCollateralPoolOwner"
fromCall.args = ["<%= settings.market9AaveId %>"]
func = "setFeatureFlagAllowAll"
args = [
    "<%= keccak256(defaultAbiCoder.encode(['bytes32','uint128'],[keccak256(hexlify('collateralPoolEnabled')),settings.market9AaveId])) %>",
    true,
]
depends = ["invoke.upgrade_core_proxy", "var.market_9aave_vars"]

[invoke.market_9aave_set_pausers_cp]
target = ["CoreProxy"]
fromCall.func = "getCollateralPoolOwner"
fromCall.args = ["<%= settings.market9AaveId %>"]
func = "setDeniers"
args = [
    "<%= keccak256(defaultAbiCoder.encode(['bytes32','uint128'],[keccak256(hexlify('collateralPoolEnabled')),settings.market9AaveId])) %>",
    [
        "<%= settings.pauser1 %>",
        "<%= settings.pauser2 %>",
        "<%= settings.pauser3 %>",
        "<%= settings.pauser4 %>",
    ],
]
depends = ["invoke.upgrade_core_proxy", "var.market_9aave_vars"]

##################################################
# Market Feature Flags
##################################################
[invoke.market_9aave_unpause_market]
target = ["PassivePerpProxy"]
fromCall.func = "owner"
func = "setFeatureFlagAllowAll"
args = [
    "<%= keccak256(defaultAbiCoder.encode(['bytes32','uint128'],[keccak256(hexlify('marketEnabled')),settings.market9AaveId])) %>",
    true,
]
depends = ["invoke.upgrade_core_proxy", "var.market_9aave_vars"]

[invoke.market_9aave_set_pausers_market]
target = ["PassivePerpProxy"]
fromCall.func = "owner"
func = "setDeniers"
args = [
    "<%= keccak256(defaultAbiCoder.encode(['bytes32','uint128'],[keccak256(hexlify('marketEnabled')),settings.market9AaveId])) %>",
    [
        "<%= settings.pauser1 %>",
        "<%= settings.pauser2 %>",
        "<%= settings.pauser3 %>",
        "<%= settings.pauser4 %>",
    ],
]
depends = ["invoke.upgrade_core_proxy", "var.market_9aave_vars"]

#####################################
# Market Configuration
#####################################
[invoke.market_9aave_set_market_config]
target = ["PassivePerpProxy"]
from = "0xE610aBbFf27E1f62F87465478EF9F8ACD1EB1656"
func = "setMarketConfiguration"
args = [
    "<%= settings.market9AaveId %>",
    { riskMatrixIndex = "<%= settings.market9Aave_riskMatrixIndex %>", maxOpenBase = "<%= parseEther(settings.market9Aave_maxOpenBaseUnscaled) %>", velocityMultiplier = "<%= parseEther(settings.market9Aave_velocityMultiplierUnscaled) %>", oracleNodeId = "<%= settings.market9Aave_oracleNodeId %>", mtmWindow = "<%= settings.market9Aave_mtmWindow %>", dutchConfig = { lambda = "<%= parseEther(settings.market9Aave_dutchConfig_lambdaUnscaled) %>", minBase = "<%= parseEther(settings.market9Aave_dutchConfig_minBaseUnscaled) %>" }, slippageParams = { phi = "<%= parseEther(settings.market9Aave_slippageParams_phiUnscaled) %>", beta = "<%= parseEther(settings.market9Aave_slippageParams_betaUnscaled) %>" }, minimumOrderBase = "<%= parseEther(settings.market9Aave_minimumOrderBaseUnscaled) %>", baseSpacing = "<%= parseEther(settings.market9Aave_baseSpacingUnscaled) %>", priceSpacing = "<%= parseEther(settings.market9Aave_priceSpacingUnscaled) %>", depthFactor = "<%= parseEther(settings.market9Aave_depthFactorUnscaled) %>", maxExposureFactor = "<%= parseEther(settings.market9Aave_maxExposureFactorUnscaled) %>", maxPSlippage = "<%= parseEther(settings.market9Aave_maxPSlippageUnscaled) %>", marketOrderMaxStaleDuration = "<%= settings.market9Aave_marketOrderMaxStaleDuration %>", priceSpread = "<%= parseEther(settings.market9Aave_priceSpreadUnscaled) %>", volatilityIndexMultiplier = "<%= parseEther(settings.market9Aave_volatilityIndexMultiplierUnscaled) %>" },
]
depends = ["invoke.create_market_9aave"]

#####################################
# Market's Collateral Pool Limits
#####################################
[invoke.market_9aave_set_cp_limits]
target = ["CoreProxy"]
fromCall.func = "getCollateralPoolOwner"
fromCall.args = ["<%= settings.market9AaveId %>"]
func = "setCollateralPoolLimits"
args = [
    "<%= settings.market9AaveId %>",
    { maxMarkets = "1", maxCollaterals = "1" },
]
depends = ["invoke.create_market_9aave"]

##################################################
# Market's Collateral Pool Insurance Fund
##################################################
[invoke.market_9aave_insurance_fund_config]
target = ["CoreProxy"]
fromCall.func = "getCollateralPoolOwner"
fromCall.args = ["<%= settings.market9AaveId %>"]
func = "configureCollateralPoolInsuranceFund"
args = [
    "<%= settings.market9AaveId %>",
    # reusing params from CP 1 since this CP will get merged
    { accountId = "<%= settings.cp1Rusd_insuranceFundAccountId %>", liquidationFee = "<%= parseEther(settings.default_insuranceFund_liquidationFeeUnscaled) %>" },
]
depends = [
    "invoke.cp_1rusd_create_insurance_fund_account",
    "invoke.create_market_9aave",
]

##################################################
# Merge Market's Collateral Pool 
##################################################
[invoke.market_9aave_merge_collateral_pool]
target = ["CoreProxy"]
fromCall.func = "owner"
func = "mergeCollateralPools"
args = ["<%= settings.market1EthId %>", "<%= settings.market9AaveId %>"]
depends = [
    "invoke.market_1eth_unpause_cp",
    "invoke.market_1eth_set_pausers_cp",
    "invoke.market_1eth_unpause_market",
    "invoke.market_1eth_set_pausers_market",
    "invoke.market_1eth_set_market_config",
    "invoke.market_1eth_set_cp_limits",
    "invoke.market_1eth_insurance_fund_config",
    "invoke.market_9aave_unpause_cp",
    "invoke.market_9aave_set_pausers_cp",
    "invoke.market_9aave_unpause_market",
    "invoke.market_9aave_set_pausers_market",
    "invoke.market_9aave_set_market_config",
    "invoke.market_9aave_set_cp_limits",
    "invoke.market_9aave_insurance_fund_config",
]
