#####################################
# Create Market
#####################################
[invoke.create_market_65syrup]
target = ["PassivePerpProxy"]
abi = "<%= JSON.stringify(contracts.PassivePerpProxy.abi.concat({'type':'event','name':'MarketDataUpdated','inputs':[{'name':'marketData','type':'tuple','indexed':false,'internalType':'struct Market.Data','components':[{'name':'id','type':'uint128','internalType':'uint128'},{'name':'passivePoolId','type':'uint128','internalType':'uint128'},{'name':'poolAccountId','type':'uint128','internalType':'uint128'},{'name':'quoteToken','type':'address','internalType':'address'},{'name':'quoteTokenDecimals','type':'uint8','internalType':'uint8'},{'name':'lastFundingVelocity','type':'int256','internalType':'SD59x18'},{'name':'lastFundingRate','type':'int256','internalType':'SD59x18'},{'name':'lastFundingTimestamp','type':'uint256','internalType':'uint256'},{'name':'lastMTM','type':'tuple','internalType':'struct PriceData','components':[{'name':'price','type':'uint256','internalType':'UD60x18'},{'name':'timestamp','type':'uint256','internalType':'uint256'}]},{'name':'longTrackers','type':'tuple','internalType':'struct FundingAndADLTrackers','components':[{'name':'fundingValue','type':'int256','internalType':'SD59x18'},{'name':'baseMultiplier','type':'uint256','internalType':'UD60x18'},{'name':'adlUnwindPrice','type':'uint256','internalType':'UD60x18'}]},{'name':'shortTrackers','type':'tuple','internalType':'struct FundingAndADLTrackers','components':[{'name':'fundingValue','type':'int256','internalType':'SD59x18'},{'name':'baseMultiplier','type':'uint256','internalType':'UD60x18'},{'name':'adlUnwindPrice','type':'uint256','internalType':'UD60x18'}]},{'name':'openInterest','type':'uint256','internalType':'UD60x18'}]},{'name':'blockTimestamp','type':'uint256','indexed':false,'internalType':'uint256'}],'anonymous':false})) %>"
fromCall.func = "owner"
func = "createMarket"
args = ["Market SYRUP", "<%= settings.pool1RusdId %>"]
var.market_65syrup.event = "MarketDataUpdated"
var.market_65syrup.arg = 0
depends = [
    "invoke.core_register_instrument_passive_perp",
    "invoke.passive_pool_create_pool_1rusd",
    "invoke.create_market_64morpho",
]

[var.market_65syrup_vars]
market65SyrupId = "<%= (String(settings.market_65syrup.id) === '65') ? settings.market_65syrup.id : parseUnits('0', 'assert market_65syrup_vars failed') %>"
depends = ["invoke.create_market_65syrup"]

##################################################
# Market's Collateral Pool Feature Flags
##################################################
[invoke.market_65syrup_unpause_cp]
target = ["CoreProxy"]
fromCall.func = "getCollateralPoolOwner"
fromCall.args = ["<%= settings.market65SyrupId %>"]
func = "setFeatureFlagAllowAll"
args = [
    "<%= keccak256(defaultAbiCoder.encode(['bytes32','uint128'],[keccak256(hexlify('collateralPoolEnabled')),settings.market65SyrupId])) %>",
    true,
]
depends = ["invoke.upgrade_core_proxy", "var.market_65syrup_vars"]

[invoke.market_65syrup_set_pausers_cp]
target = ["CoreProxy"]
fromCall.func = "getCollateralPoolOwner"
fromCall.args = ["<%= settings.market65SyrupId %>"]
func = "setDeniers"
args = [
    "<%= keccak256(defaultAbiCoder.encode(['bytes32','uint128'],[keccak256(hexlify('collateralPoolEnabled')),settings.market65SyrupId])) %>",
    [
        "<%= settings.pauser1 %>",
        "<%= settings.pauser2 %>",
        "<%= settings.pauser3 %>",
        "<%= settings.pauser4 %>",
    ],
]
depends = ["invoke.upgrade_core_proxy", "var.market_65syrup_vars"]

##################################################
# Market Feature Flags
##################################################
[invoke.market_65syrup_unpause_market]
target = ["PassivePerpProxy"]
fromCall.func = "owner"
func = "setFeatureFlagAllowAll"
args = [
    "<%= keccak256(defaultAbiCoder.encode(['bytes32','uint128'],[keccak256(hexlify('marketEnabled')),settings.market65SyrupId])) %>",
    true,
]
depends = ["invoke.upgrade_core_proxy", "var.market_65syrup_vars"]

[invoke.market_65syrup_set_pausers_market]
target = ["PassivePerpProxy"]
fromCall.func = "owner"
func = "setDeniers"
args = [
    "<%= keccak256(defaultAbiCoder.encode(['bytes32','uint128'],[keccak256(hexlify('marketEnabled')),settings.market65SyrupId])) %>",
    [
        "<%= settings.pauser1 %>",
        "<%= settings.pauser2 %>",
        "<%= settings.pauser3 %>",
        "<%= settings.pauser4 %>",
    ],
]
depends = ["invoke.upgrade_core_proxy", "var.market_65syrup_vars"]

[invoke.market_65syrup_enabled_zero_fee_option]
target = ["PassivePerpProxy"]
fromCall.func = "owner"
func = "setAdmins"
args = [
    "<%= keccak256(defaultAbiCoder.encode(['bytes32','uint128'],[keccak256(hexlify('marketZeroFees')),settings.market65SyrupId])) %>",
    [
        "<%= settings.setMarketZeroFeeBot %>",
    ],
]
depends = ["invoke.upgrade_passive_perp_proxy", "var.market_65syrup_vars"]

#####################################
# Market Configuration
#####################################
[invoke.market_65syrup_set_market_config]
target = ["PassivePerpProxy"]
from = "0xE610aBbFf27E1f62F87465478EF9F8ACD1EB1656"
func = "setMarketConfiguration"
args = [
    "<%= settings.market65SyrupId %>",
    { riskMatrixIndex = "<%= settings.market65Syrup_riskMatrixIndex %>", maxOpenBase = "<%= parseEther(settings.market65Syrup_maxOpenBaseUnscaled) %>", velocityMultiplier = "<%= parseEther(settings.market65Syrup_velocityMultiplierUnscaled) %>", oracleNodeId = "<%= settings.market65Syrup_oracleNodeId %>", mtmWindow = "<%= settings.market65Syrup_mtmWindow %>", dutchConfig = { lambda = "<%= parseEther(settings.market65Syrup_dutchConfig_lambdaUnscaled) %>", minBase = "<%= parseEther(settings.market65Syrup_dutchConfig_minBaseUnscaled) %>" }, slippageParams = { phi = "<%= parseEther(settings.market65Syrup_slippageParams_phiUnscaled) %>", beta = "<%= parseEther(settings.market65Syrup_slippageParams_betaUnscaled) %>" }, minimumOrderBase = "<%= parseEther(settings.market65Syrup_minimumOrderBaseUnscaled) %>", baseSpacing = "<%= parseEther(settings.market65Syrup_baseSpacingUnscaled) %>", priceSpacing = "<%= parseEther(settings.market65Syrup_priceSpacingUnscaled) %>", depthFactor = "<%= parseEther(settings.market65Syrup_depthFactorUnscaled) %>", maxExposureFactor = "<%= parseEther(settings.market65Syrup_maxExposureFactorUnscaled) %>", maxPSlippage = "<%= parseEther(settings.market65Syrup_maxPSlippageUnscaled) %>", marketOrderMaxStaleDuration = "<%= settings.market65Syrup_marketOrderMaxStaleDuration %>", priceSpread = "<%= parseEther(settings.market65Syrup_priceSpreadUnscaled) %>", volatilityIndexMultiplier = "<%= parseEther(settings.market65Syrup_volatilityIndexMultiplierUnscaled) %>" },
]
depends = ["invoke.create_market_65syrup"]

#####################################
# Market's Collateral Pool Limits
#####################################
[invoke.market_65syrup_set_cp_limits]
target = ["CoreProxy"]
fromCall.func = "getCollateralPoolOwner"
fromCall.args = ["<%= settings.market65SyrupId %>"]
func = "setCollateralPoolLimits"
args = [
    "<%= settings.market65SyrupId %>",
    { maxMarkets = "1", maxCollaterals = "1" },
]
depends = ["invoke.create_market_65syrup"]

##################################################
# Market's Collateral Pool Insurance Fund
##################################################
[invoke.market_65syrup_insurance_fund_config]
target = ["CoreProxy"]
fromCall.func = "getCollateralPoolOwner"
fromCall.args = ["<%= settings.market65SyrupId %>"]
func = "configureCollateralPoolInsuranceFund"
args = [
    "<%= settings.market65SyrupId %>",
    # reusing params from CP 1 since this CP will get merged
    { accountId = "<%= settings.cp1Rusd_insuranceFundAccountId %>", liquidationFee = "<%= parseEther(settings.default_insuranceFund_liquidationFeeUnscaled) %>" },
]
depends = [
    "invoke.cp_1rusd_create_insurance_fund_account",
    "invoke.create_market_65syrup",
]

##################################################
# Merge Market's Collateral Pool 
##################################################
[invoke.market_65syrup_merge_collateral_pool]
target = ["CoreProxy"]
fromCall.func = "owner"
func = "mergeCollateralPools"
args = ["<%= settings.market1EthId %>", "<%= settings.market65SyrupId %>"]
depends = [
    "invoke.market_1eth_unpause_cp",
    "invoke.market_1eth_set_pausers_cp",
    "invoke.market_1eth_unpause_market",
    "invoke.market_1eth_set_pausers_market",
    "invoke.market_1eth_set_market_config",
    "invoke.market_1eth_set_cp_limits",
    "invoke.market_1eth_insurance_fund_config",
    "invoke.market_65syrup_unpause_cp",
    "invoke.market_65syrup_set_pausers_cp",
    "invoke.market_65syrup_unpause_market",
    "invoke.market_65syrup_set_pausers_market",
    "invoke.market_65syrup_set_market_config",
    "invoke.market_65syrup_set_cp_limits",
    "invoke.market_65syrup_insurance_fund_config",
]
