[invoke.oracle_manager_register_node_wbtc_usd_stork]
target = ["OracleManagerProxy"]
fromCall.func = "owner"
func = "registerNode"
args = [
    "<%= settings.ORACLE_MANAGER_NODE_TYPE_STORK_OFFCHAIN_LOOKUP %>",
    "<%= defaultAbiCoder.encode(['address','string'], [contracts.OracleAdaptersProxy.address, settings.storkAssetPairIdWBTC]) %>",
    [
    ],
]
var.wbtcUsdNodeIdStork.event = "NodeRegistered"
var.wbtcUsdNodeIdStork.arg = 0
depends = ["invoke.upgrade_oracle_manager_proxy"]

[invoke.oracle_manager_wbtc_usd_stork_max_stale_duration]
target = ["OracleManagerProxy"]
fromCall.func = "owner"
func = "setMaxStaleDuration"
args = [
    "<%= settings.wbtcUsdNodeIdStork %>",
    "<%= settings.wbtcUsdMaxStaleDurationStork %>",
]
depends = ["invoke.oracle_manager_register_node_wbtc_usd_stork"]
