[invoke.oracle_manager_register_node_wbtc_usdc_stork]
target = ["OracleManagerProxy"]
fromCall.func = "owner"
func = "registerNode"
args = [
    "<%= settings.ORACLE_MANAGER_NODE_TYPE_DIV_REDUCER %>",
    "0x",
    [
        "<%= settings.wbtcUsdNodeIdStork %>",
        "<%= settings.usdcUsdNodeIdStork %>",
    ],
]
var.wbtcUsdcNodeIdStork.event = "NodeRegistered"
var.wbtcUsdcNodeIdStork.arg = 0
depends = ["invoke.upgrade_oracle_manager_proxy"]

[invoke.oracle_manager_wbtc_usdc_stork_max_stale_duration]
target = ["OracleManagerProxy"]
fromCall.func = "owner"
func = "setMaxStaleDuration"
args = [
    "<%= settings.wbtcUsdcNodeIdStork %>",
    "<%= settings.wbtcUsdcMaxStaleDurationStork %>",
]
depends = ["invoke.oracle_manager_register_node_wbtc_usdc_stork"]