# Configure chainA endpoint to receive messages from chainB
[invoke.lz_set_destination_receive_config]
target = ["<%= settings.chainAEndpointAddress %>"]
abi = "[{\"inputs\":[{\"internalType\":\"address\",\"name\":\"oapp\",\"type\":\"address\"},{\"internalType\":\"address\",\"name\":\"lib\",\"type\":\"address\"},{\"components\":[{\"internalType\":\"uint32\",\"name\":\"eid\",\"type\":\"uint32\"},{\"internalType\":\"uint32\",\"name\":\"configType\",\"type\":\"uint32\"},{\"internalType\":\"bytes\",\"name\":\"config\",\"type\":\"bytes\"}],\"internalType\":\"struct SetConfigParam[]\",\"name\":\"params\",\"type\":\"tuple[]\"}],\"name\":\"setConfig\",\"outputs\":[],\"stateMutability\":\"nonpayable\",\"type\":\"function\"}]"
fromCall.func = "owner"
func = "setConfig"
args = [
    "<%= settings.chainAOAppAddress %>",
    "<%= settings.chainAReceiveLibAddress %>",
    [
        {eid = "<%= settings.chainBEid %>",configType = 2,config = "<%= defaultAbiCoder.encode(['uint64', 'uint8', 'uint8', 'uint8', 'address[]', 'address[]'],[settings.chainALzConfirmations, settings.lzRequiredDVNCount, settings.lzOptionalDVNCount, settings.lzOptionalDVNThreshold, [settings.chainALzRequiredDVN1], []]) %>"}
    ]
]
depends = ["invoke.lz_set_source_send_config"]
